name: "build"

env:
  GODOT_VERSION: 4.4
  EXPORT_NAME: damsels-gambit
  PROJECT_PATH: .

on:
  workflow_call:
  workflow_dispatch:
  push:
    tags-ignore: ['v*.*.*']
    paths:
      - "**.gd" # all gdscript files
      - "**.cs" # all C# files
      - "**.tscn" # scene files
      - "**.import" # this means an asset changed
      - "**.tres" # godot resources
      - "export_presets.cfg" # the export template
      - "project.godot"
      - "**.csproj"

jobs:
  windows:
    name: Windows Build
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:mono-4.4
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: .NET installation
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.config/
          mv /root/.config/godot ~/.config/godot
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable.mono ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable.mono
      - name: Build
        run: |
          mkdir -v -p build
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Windows Desktop" "$EXPORT_DIR/$EXPORT_NAME.zip"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: build/$EXPORT_NAME.zip

  macos:
    name: MacOS Build
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:mono-4.4
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: .NET installation
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable.mono ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable.mono
      - name: Build
        run: |
          mkdir -v -p build
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "macOS" "$EXPORT_DIR/$EXPORT_NAME.zip"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos
          path: build/$EXPORT_NAME.zip