name: Create release

env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true

on:
  push:
    tags: ['v*.*.*']

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build.yml
  release:
    name: Release pushed tag
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Create release
        uses: spenserblack/actions-tag-to-release@main
        with:
          tag-as-title: true
          prerelease: auto
      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: windows
          path: windows
      - name: Zip up Windows Artifact
        run: zip -r windows.zip windows/*
      - name: Download Linux Artifact
        uses: actions/download-artifact@v4
        with:
          name: linux
          path: linux
      - name: Zip up Linux Artifact
        run: zip -r linux.zip linux/*
      - name: Download Mac Artifact
        uses: actions/download-artifact@v4
        with:
          name: mac
          path: mac
      - name: Zip up Mac Artifact
        run: zip -r mac.zip mac/*
      - name: Upload artifacts to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release upload "$tag" \
            windows.zip \
            linux.zip \
            mac.zip \
            --repo="$GITHUB_REPOSITORY"
      